Change exceptions.VersionMismatch into warning
ipfs-shipyard/py-ipfs-http-client pull request #253
Opened 2021-03-31 08:53 UTC by dokterbob

Let users decide whether they’re willing to take the risk; most of IPFS’ API doesn’t change between versions.

I was unable to run tests locally and the tests in the default branch are broken. Manual evaluation of CI test results is required.

2021-03-31 09:08 UTC, dokterbob commented
I've manually evaluated all the tests and anything working in `master` is working here as well, including the modified tests for `VersionMismatch` warnings. I think it's ready for merge (pending maintainer feedback).

Ref: https://travis-ci.com/github/ipfs-shipyard/py-ipfs-http-client/jobs/495154225#L375

2021-03-31 20:35 UTC, ntninja commented
I agree with this nowadays. Back in the 0.4.x days the breakage thing was pretty bad, but it's been a while and things seem to have settled down. Thank you for the suggestion!

The Windows error looks like they stopped distributing Python from Chocolatey. \*sigh\*
Will look more into this (and your PR) in the next couple of days.

2021-04-02 07:08 UTC, 0kalekale commented
how long untill this gets upstreamed?

2021-04-03 13:53 UTC, ntninja requested changes
Good! Tests can be shortened quite a bit using `pytest.warns` through.

2021-04-03 13:53 UTC, ntninja commented on test/unit/test_client.py
> +		assert issubclass(w[-1].category, ipfshttpclient.exceptions.VersionMismatch)
Please use [`pytest.warns`](https://docs.pytest.org/en/stable/reference.html#pytest-warns) as it makes for more easily readable code.

2021-04-03 13:53 UTC, ntninja commented on test/unit/test_client.py
> +		assert len(w) == 0
This first assertion can apparently also be shortend using `pytest.warns`: https://stackoverflow.com/a/45671804/277882

2021-04-09 20:29 UTC, c0llab0rat0r commented
A rebase of this branch will fix its build failure.

2021-04-09 21:02 UTC, closed without merging